import { IMAGE_SIZES } from "@/lib/image-settings";

/** Responsive header logo widths generated by scripts/generate-logo-variants.mjs */
export const LOGO_WIDTHS = [256, 384, 512, 640] as const;

export const LOGO_DEFAULT_SRC = "/logo.png";

export const LOGO_SRCSET = LOGO_WIDTHS.map((w) => `/logo-${w}.webp ${w}w`).join(", ");

export const LOGO_SIZES = IMAGE_SIZES.logo;
