import { resolveImagePreset, type ImagePreset } from "@/lib/image-settings";
import { RESPONSIVE_IMAGE_MANIFEST } from "@/lib/responsive-image-manifest";

export type OptimizedImageOptions = {
  src: string;
  alt: string;
  title?: string;
  priority?: boolean;
  preset?: ImagePreset;
  sizes?: string;
  objectFit?: "cover" | "contain";
};

function variantPath(src: string, width: number): string {
  return src.replace(/\.[^.]+$/i, `.w${width}.webp`);
}

/**
 * Keep the original file as `src` (never breaks if WebP is missing).
 * Add WebP srcSet from the build-time manifest (generated by images:responsive).
 * No node:fs here — this module is shared with client components.
 */
export function optimizedImageProps({
  src,
  alt,
  title,
  priority,
  preset,
  sizes,
}: OptimizedImageOptions) {
  const presetOpts = resolveImagePreset(preset);
  const isHero = preset === "hero" || preset === "heroSide";
  const widths = RESPONSIVE_IMAGE_MANIFEST[src];

  const base = {
    src,
    alt,
    title: title ?? alt,
    decoding: priority || isHero ? ("sync" as const) : ("async" as const),
    fetchPriority: priority || isHero ? ("high" as const) : ("auto" as const),
    loading: "eager" as const,
    sizes: sizes ?? presetOpts?.sizes ?? "100vw",
  };

  if (!widths?.length) return base;

  const sorted = [...widths].sort((a, b) => a - b);
  return {
    ...base,
    srcSet: sorted.map((w) => `${variantPath(src, w)} ${w}w`).join(", "),
  };
}
