/** Auto-generated by scripts/generate-responsive-images.mjs — do not edit. */
export const RESPONSIVE_IMAGE_MANIFEST: Record<string, number[]> = {
  "/images/bird-spikes/spike3.webp": [
    640,
    1280
  ],
  "/images/child-safety-nets/child-1.jpg": [
    640,
    1280
  ],
  "/images/cloth-hangers/cloth7.webp": [
    640,
    1280
  ],
  "/images/cloth-hangers/cloth8.jpeg": [
    640,
    1280
  ],
  "/images/cloth-hangers/cloth9.jpeg": [
    640,
    1280
  ],
  "/images/cloth-hangers/whatsapp-image-2026-07-04-at-090739.jpeg": [
    640,
    1280
  ],
  "/images/cricket-nets/n11.jpg": [
    640,
    1280
  ],
  "/images/cricket-nets/sp-2.jpg": [
    640,
    1280
  ],
  "/images/deva-logo.png": [
    640,
    1280
  ],
  "/images/duct-area-nets/car-1.jpg": [
    640,
    1280
  ],
  "/images/duct-area-nets/dc6.jpg": [
    640,
    1280
  ],
  "/images/duct-area-nets/dc7.jpg": [
    640,
    1280
  ],
  "/images/duct-area-nets/dc8.jpg": [
    640,
    1280
  ],
  "/images/duct-area-nets/indusrties-3.jpg": [
    640,
    1280
  ],
  "/images/duct-area-nets/industries-2.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i1.png": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i15.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i3.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i4.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i5.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i6.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/i7.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/img20251025132727jpg.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n1.webp": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n26.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n31.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n40.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n48.webp": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n50.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n52.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/n53.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100255.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100305.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100308.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100311.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100325.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100331.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100336.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100342.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100351.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100359.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100403.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100406.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100717.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100719.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100720.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100723.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100725.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100726.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100727.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100728.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100735.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100736.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100737.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100742.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100743.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100756.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100815.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100821.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-100824.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101249-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101249.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101251.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101252.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101253.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101254.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101255.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101256.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101258.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101259.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101300.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101301-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101301-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101301.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101302-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101302.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101303.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101304.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101305-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101305-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101305.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101308-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101308.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101309-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101309.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101312-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101312.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101313-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101313-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101313.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101314-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101314.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101316.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101317-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101317-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101317.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101318-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101318.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101319.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101321-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101321.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101322-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101322.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101323.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101324.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101325-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101325.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101326.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101327-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101327.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101328-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101328-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101328.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101329-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101329.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101330-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101330.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101331-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101331.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101332.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101333-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101333.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101334-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101334-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101334.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101335.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101336-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101336.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101337-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101337.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101338-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101338.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101339-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101339.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101340-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101340-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101340.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101341-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101341.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101342.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101343-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101343-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101343.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101344-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101344.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101345-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101345-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101345.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101346-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101346.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101347-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101347.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101348-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101348.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101349-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101349.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101350-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101350.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101351-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101351.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101352.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101354-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101354-2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101354.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101355-1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-balcony/whatsapp-image-2026-06-26-at-101355.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/i14.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/i16.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/n44.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/n50.jpg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/o1.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/o2.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/o3.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100334.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100336.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100338.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100340.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100359.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100730.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-100741.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-101314.jpeg": [
    640,
    1280
  ],
  "/images/invisible-grill-window/whatsapp-image-2026-06-26-at-101322.jpeg": [
    640,
    1280
  ],
  "/images/mosquito-nets/mosq1.png": [
    640,
    1280
  ],
  "/images/mosquito-nets/n21.jpg": [
    640,
    1280
  ],
  "/images/pet-safety-nets/pet-2.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b-17.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b-18.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b1.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b10.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b13.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b15.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b2.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b3.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b5.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b6.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/b8.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/img-20260214-wa0017.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/img20251003165138jpg.jpeg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/n53.jpg": [
    640,
    1280
  ],
  "/images/safety-nets-balcony/whatsapp-image-2026-07-04-at-091404.jpeg": [
    640,
    1280
  ]
};
